title: "Nato Family's Site"
author: "Dudu Nato"
email: alo@natofamily.xyz
github_username: dudunato
twitter_username: dudunato
facebook_username: natofamily
keywords: "comma, separated, keywords"
description: "Nato Family in Missions"

baseurl: "/familysite/" # prod
url: "http://dudunato.github.io/" # prod
# baseurl: "" # dev
# url: "" # dev

markdown: redcarpet
redcarpet:
  extensions: ["smart", "autolink", "tables", "no_intra_emphasis", "strikethrough", "underline", "quote", "footnotes"]

exclude: ['assets/src', 'node_modules', 'package.json', 'gulpfile.js', 'LICENSE', 'README.md', 'bower_components', 'bower.json']

timezone: Europe/Switzerland

permalink: /:title/

languages: ['en', 'br']

paginate: 5
paginate_path: "/page:num"
